### ISSUE TITLE
I can't get the 00-starter-seed python example to work (singature verification failed)

### ISSUE THREAD

**Issue by mRcSchwering** [auth0-samples/auth0-python-api-samples#42]
Hi,

I am trying to validate the signature of AzureAD issued access tokens using thecode described here: https://github.com/auth0-samples/auth0-python-api-samples/blob/master/00-Starter-Seed/server.py#L113

Python raises in this line https://github.com/auth0-samples/auth0-python-api-samples/blob/master/00-Starter-Seed/server.py#L113 with 

```
Traceback (most recent call last):
  File "/home/vagrant/anaconda3/lib/python3.7/site-packages/jose/jws.py", line 269, in _verify_signature
    raise JWSSignatureError()
jose.exceptions.JWSSignatureError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/anaconda3/lib/python3.7/site-packages/jose/jwt.py", line 154, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
  File "/home/vagrant/anaconda3/lib/python3.7/site-packages/jose/jws.py", line 80, in verify
    _verify_signature(signing_input, header, signature, key, algorithms)
  File "/home/vagrant/anaconda3/lib/python3.7/site-packages/jose/jws.py", line 271, in _verify_signature
    raise JWSError('Signature verification failed.')
jose.exceptions.JWSError: Signature verification failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/home/vagrant/anaconda3/lib/python3.7/site-packages/jose/jwt.py", line 156, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Signature verification failed.
```

I am using an implicit flow and acquire tokens using https://oidcdebugger.com/debug.
Currently I am trying to validate the signature of the (access) token.
For keys I am using the endpoint described in the metadata endpoint: https://login.microsoftonline.com/{tenant_id}/discovery/v2.0/keys

1. I extract the key where `kid` matched the one of the token header
2. I construct the dict with `kid`, `kty`, `use`, `n`, `e`
3. then use it with `jose.jwt.decode`

I don't understand why the singatures dont match. Am I using the wrong ones?

**Comment by mRcSchwering** [comment]
Oh, I think I found the error.

I am supposed to validate the id_token, not the access token, right?
The id_token validation works.
